# Added by Armbian
#
# Reference: https://netplan.readthedocs.io/en/stable/netplan-yaml/
#
# Let systemd-networkd manage all Ethernet devices on this system, but be configured by Netplan.

network:
  version: 2
  renderer: networkd
  ethernets:
    all-eth-interfaces:
      match:
        name: "end*"
      dhcp4: yes
      dhcp6: yes
      ipv6-privacy: yes
    wlan0:                  #for wifi AP static address
      addresses:
        - 172.24.1.1/24
    eth1:                   #for Huawei E3372-607 G4-modem
      dhcp4: true
      match:
        macaddress: 0c:5b:8f:27:9a:64
      set-name: eth1        #rename by mac address
